### ISSUE TITLE
배포 작업

### ISSUE THREAD

**Issue by cookie-meringue** [mju-likelion/bagel#3]
## Description
배포 작업
### AWS를 사용한 배포
- [x] 도메인 구매
- [x] https 인증서 발급
- [x] Route53 도메인 연결
- [x] EC2 생성
- [ ] RDS 생성
이후 상황에 따라 추가 작업 
## Additional context
공부 필요

**Comment by zelkovaria** [comment]
배포 천재. 스프링 천재. 한국어, 영어, 그리고 JAVA,,, 3개 외국어 능력자,,,
